export { default as Title } from './title/Title'
export { default as LargeTitle } from './largeTitle/LargeTitle'
export { default as Link } from './link/Link'
export { default as LangBar } from './langBar/LangBar'
export { default as SocialLink } from './socialLink/SocialLink'
export { default as Email } from './email/Email'